
POST http://localhost:3003/createUser
Content-Type: application/json

{
	"name": "Pam Beasly",
  	"email": "pam@dundermifflin.com",
  	"password": "fa8s7e6fia7se6ga8i67gf9a7se6f8a7s6e5gaes"
}

###

GET http://localhost:3003/all
Content-Type: application/json

###

DELETE http://localhost:3003/1673999339910
Content-Type: application/json

###